package szaman.playbook.entity;
// Generated 2018-01-01 03:41:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auditorium generated by hbm2java
 */
@Entity
@Table(name="auditorium")
public class Auditorium  implements java.io.Serializable {


     private int auditoriumId;
     private Theatre theatre;
     private int auditoriumNumber;
     private int noSlots;
     private String missingSlots;
     private String auditoriumType;
     private Set shows = new HashSet(0);

    public Auditorium() {
    }

	
    public Auditorium(int auditoriumId, Theatre theatre, int auditoriumNumber, int noSlots, String auditoriumType) {
        this.auditoriumId = auditoriumId;
        this.theatre = theatre;
        this.auditoriumNumber = auditoriumNumber;
        this.noSlots = noSlots;
        this.auditoriumType = auditoriumType;
    }
    public Auditorium(int auditoriumId, Theatre theatre, int auditoriumNumber, int noSlots, String missingSlots, String auditoriumType, Set shows) {
       this.auditoriumId = auditoriumId;
       this.theatre = theatre;
       this.auditoriumNumber = auditoriumNumber;
       this.noSlots = noSlots;
       this.missingSlots = missingSlots;
       this.auditoriumType = auditoriumType;
       this.shows = shows;
    }
   
     @Id 

    
    @Column(name="auditorium_id", unique=true, nullable=false)
    public int getAuditoriumId() {
        return this.auditoriumId;
    }
    
    public void setAuditoriumId(int auditoriumId) {
        this.auditoriumId = auditoriumId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="theatre_id", nullable=false)
    public Theatre getTheatre() {
        return this.theatre;
    }
    
    public void setTheatre(Theatre theatre) {
        this.theatre = theatre;
    }

    
    @Column(name="auditorium_number", nullable=false)
    public int getAuditoriumNumber() {
        return this.auditoriumNumber;
    }
    
    public void setAuditoriumNumber(int auditoriumNumber) {
        this.auditoriumNumber = auditoriumNumber;
    }

    
    @Column(name="no_slots", nullable=false)
    public int getNoSlots() {
        return this.noSlots;
    }
    
    public void setNoSlots(int noSlots) {
        this.noSlots = noSlots;
    }

    
    @Column(name="missing_slots")
    public String getMissingSlots() {
        return this.missingSlots;
    }
    
    public void setMissingSlots(String missingSlots) {
        this.missingSlots = missingSlots;
    }

    
    @Column(name="auditorium_type", nullable=false)
    public String getAuditoriumType() {
        return this.auditoriumType;
    }
    
    public void setAuditoriumType(String auditoriumType) {
        this.auditoriumType = auditoriumType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="auditorium")
    public Set getShows() {
        return this.shows;
    }
    
    public void setShows(Set shows) {
        this.shows = shows;
    }




}


