package szaman.playbook.entity;
// Generated 2018-01-01 03:41:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Play generated by hbm2java
 */
@Entity
@Table(name="play"
)
public class Play  implements java.io.Serializable {


     private int playId;
     private String name;
     private String description;
     private String genre;
     private Set shows = new HashSet(0);

    public Play() {
    }

	
    public Play(int playId, String name, String description, String genre) {
        this.playId = playId;
        this.name = name;
        this.description = description;
        this.genre = genre;
    }
    public Play(int playId, String name, String description, String actors, String genre, Set shows) {
       this.playId = playId;
       this.name = name;
       this.description = description;
       this.genre = genre;
       this.shows = shows;
    }
   
     @Id 

    
    @Column(name="play_id", unique=true, nullable=false)
    public int getPlayId() {
        return this.playId;
    }
    
    public void setPlayId(int playId) {
        this.playId = playId;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=1000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="genre", nullable=false, length=50)
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="play")
    public Set getShows() {
        return this.shows;
    }
    
    public void setShows(Set shows) {
        this.shows = shows;
    }




}


