package szaman.playbook.entity;
// Generated 2018-01-01 03:41:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
)
public class Reservation  implements java.io.Serializable {


     private int reservationId;
     private Account account;
     private Show show;
     private int noSlots;
     private String slotsId;
     private int noNormal;
     private int noHalf;
     private float price;

    public Reservation() {
    }

    public Reservation(int reservationId, Account account, Show show, int noSlots, String slotsId, int noNormal, int noHalf, float price) {
       this.reservationId = reservationId;
       this.account = account;
       this.show = show;
       this.noSlots = noSlots;
       this.slotsId = slotsId;
       this.noNormal = noNormal;
       this.noHalf = noHalf;
       this.price = price;
    }
   
     @Id 

    
    @Column(name="reservation_id", unique=true, nullable=false)
    public int getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(int reservationId) {
        this.reservationId = reservationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_id", nullable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="show_id", nullable=false)
    public Show getShow() {
        return this.show;
    }
    
    public void setShow(Show show) {
        this.show = show;
    }

    
    @Column(name="no_slots", nullable=false)
    public int getNoSlots() {
        return this.noSlots;
    }
    
    public void setNoSlots(int noSlots) {
        this.noSlots = noSlots;
    }

    
    @Column(name="slots_id", nullable=false, length=200)
    public String getSlotsId() {
        return this.slotsId;
    }
    
    public void setSlotsId(String slotsId) {
        this.slotsId = slotsId;
    }

    
    @Column(name="no_normal", nullable=false)
    public int getNoNormal() {
        return this.noNormal;
    }
    
    public void setNoNormal(int noNormal) {
        this.noNormal = noNormal;
    }

    
    @Column(name="no_half", nullable=false)
    public int getNoHalf() {
        return this.noHalf;
    }
    
    public void setNoHalf(int noHalf) {
        this.noHalf = noHalf;
    }

    
    @Column(name="price", nullable=false, precision=8, scale=8)
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }




}


