/*
 * Praca Inzynierska - Czesc 3 - Aplikacja Webowa do obslugi sieci Teatrow
 *
 * Klasa modelu Account (mapowanie Hibernate) - Account.java.
 * 
 */

package szaman.playbook.entity;
// Generated 2017-12-15 00:56:10 by Hibernate Tools 4.3.1

// Laczenie z reszta wlasnych klas //



// Reszta klas //

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Theatre generated by hbm2java
 */
@Entity
@Table(name="theatre", uniqueConstraints = @UniqueConstraint(columnNames="phone_number"))

public class Theatre  implements java.io.Serializable 
{
    private int theatreId;
    private String voivodeship;
    private String city;
    private String street;
    private int phoneNumber;
    private String name;
    private Set auditoriums = new HashSet(0);

    public Theatre() 
    {
        
    }
	
    public Theatre(int theatreId, String voivodeship, String city, String street, int phoneNumber) 
    {
        this.theatreId = theatreId;
        this.voivodeship = voivodeship;
        this.city = city;
        this.street = street;
        this.phoneNumber = phoneNumber;
    }
    
    public Theatre(int theatreId, String voivodeship, String city, String street, int phoneNumber, String name, Set auditoriums) 
    {
        this.theatreId = theatreId;
        this.voivodeship = voivodeship;
        this.city = city;
        this.street = street;
        this.phoneNumber = phoneNumber;
        this.name = name;
        this.auditoriums = auditoriums;
    }
   
    @Id 
    
    @Column(name="theatre_id", unique=true, nullable=false)
    public int getTheatreId()
    {
        return this.theatreId;
    }
    
    public void setTheatreId(int theatreId) 
    {
        this.theatreId = theatreId;
    }
    
    @Column(name="voivodeship", nullable=false, length=100)
    public String getVoivodeship() 
    {
        return this.voivodeship;
    }
    
    public void setVoivodeship(String voivodeship) 
    {
        this.voivodeship = voivodeship;
    }
    
    @Column(name="city", nullable=false, length=100)
    public String getCity()
    {
        return this.city;
    }
    
    public void setCity(String city) 
    {
        this.city = city;
    }
    
    @Column(name="street", nullable=false, length=100)
    public String getStreet() 
    {
        return this.street;
    }
    
    public void setStreet(String street) 
    {
        this.street = street;
    }
    
    @Column(name="phone_number", unique=true, nullable=false)
    public int getPhoneNumber()
    {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(int phoneNumber) 
    {
        this.phoneNumber = phoneNumber;
    }
    
    @Column(name="name")
    public String getName() 
    {
        return this.name;
    }
    
    public void setName(String name)
    {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="theatre")
    public Set getAuditoriums()
    {
        return this.auditoriums;
    }
    
    public void setAuditoriums(Set auditoriums) 
    {
        this.auditoriums = auditoriums;
    }
}


